# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/FlashRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/FlashRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/FlashRT/CMakeFiles /data/FlashRT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/FlashRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cutlass_ada_fp8_obj

# Build rule for target.
cutlass_ada_fp8_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cutlass_ada_fp8_obj
.PHONY : cutlass_ada_fp8_obj

# fast build rule for target.
cutlass_ada_fp8_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_obj.dir/build
.PHONY : cutlass_ada_fp8_obj/fast

#=============================================================================
# Target rules for targets named cutlass_ada_fp8_simple_obj

# Build rule for target.
cutlass_ada_fp8_simple_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cutlass_ada_fp8_simple_obj
.PHONY : cutlass_ada_fp8_simple_obj

# fast build rule for target.
cutlass_ada_fp8_simple_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_simple_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_simple_obj.dir/build
.PHONY : cutlass_ada_fp8_simple_obj/fast

#=============================================================================
# Target rules for targets named fa2_vendor_obj

# Build rule for target.
fa2_vendor_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fa2_vendor_obj
.PHONY : fa2_vendor_obj

# fast build rule for target.
fa2_vendor_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/build
.PHONY : fa2_vendor_obj/fast

#=============================================================================
# Target rules for targets named flash_rt_fa2

# Build rule for target.
flash_rt_fa2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash_rt_fa2
.PHONY : flash_rt_fa2

# fast build rule for target.
flash_rt_fa2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_fa2.dir/build.make CMakeFiles/flash_rt_fa2.dir/build
.PHONY : flash_rt_fa2/fast

#=============================================================================
# Target rules for targets named flash_rt_kernels

# Build rule for target.
flash_rt_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash_rt_kernels
.PHONY : flash_rt_kernels

# fast build rule for target.
flash_rt_kernels/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/build
.PHONY : flash_rt_kernels/fast

csrc/attention/fa2_wrapper.o: csrc/attention/fa2_wrapper.cu.o
.PHONY : csrc/attention/fa2_wrapper.o

# target to build an object file
csrc/attention/fa2_wrapper.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/fa2_wrapper.cu.o
.PHONY : csrc/attention/fa2_wrapper.cu.o

csrc/attention/fa2_wrapper.i: csrc/attention/fa2_wrapper.cu.i
.PHONY : csrc/attention/fa2_wrapper.i

# target to preprocess a source file
csrc/attention/fa2_wrapper.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/fa2_wrapper.cu.i
.PHONY : csrc/attention/fa2_wrapper.cu.i

csrc/attention/fa2_wrapper.s: csrc/attention/fa2_wrapper.cu.s
.PHONY : csrc/attention/fa2_wrapper.s

# target to generate assembly for a file
csrc/attention/fa2_wrapper.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/fa2_wrapper.cu.s
.PHONY : csrc/attention/fa2_wrapper.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.cu.s

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.o: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.o

# target to build an object file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.o
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.o

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.i: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.i

# target to preprocess a source file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.i
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.i

csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.s: csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.s

# target to generate assembly for a file
csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa2_vendor_obj.dir/build.make CMakeFiles/fa2_vendor_obj.dir/csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.s
.PHONY : csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.cu.s

csrc/attention/fmha_dispatch.o: csrc/attention/fmha_dispatch.cu.o
.PHONY : csrc/attention/fmha_dispatch.o

# target to build an object file
csrc/attention/fmha_dispatch.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/attention/fmha_dispatch.cu.o
.PHONY : csrc/attention/fmha_dispatch.cu.o

csrc/attention/fmha_dispatch.i: csrc/attention/fmha_dispatch.cu.i
.PHONY : csrc/attention/fmha_dispatch.i

# target to preprocess a source file
csrc/attention/fmha_dispatch.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/attention/fmha_dispatch.cu.i
.PHONY : csrc/attention/fmha_dispatch.cu.i

csrc/attention/fmha_dispatch.s: csrc/attention/fmha_dispatch.cu.s
.PHONY : csrc/attention/fmha_dispatch.s

# target to generate assembly for a file
csrc/attention/fmha_dispatch.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/attention/fmha_dispatch.cu.s
.PHONY : csrc/attention/fmha_dispatch.cu.s

csrc/bindings.o: csrc/bindings.cpp.o
.PHONY : csrc/bindings.o

# target to build an object file
csrc/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/bindings.cpp.o
.PHONY : csrc/bindings.cpp.o

csrc/bindings.i: csrc/bindings.cpp.i
.PHONY : csrc/bindings.i

# target to preprocess a source file
csrc/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/bindings.cpp.i
.PHONY : csrc/bindings.cpp.i

csrc/bindings.s: csrc/bindings.cpp.s
.PHONY : csrc/bindings.s

# target to generate assembly for a file
csrc/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/bindings.cpp.s
.PHONY : csrc/bindings.cpp.s

csrc/fa2_bindings.o: csrc/fa2_bindings.cpp.o
.PHONY : csrc/fa2_bindings.o

# target to build an object file
csrc/fa2_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_fa2.dir/build.make CMakeFiles/flash_rt_fa2.dir/csrc/fa2_bindings.cpp.o
.PHONY : csrc/fa2_bindings.cpp.o

csrc/fa2_bindings.i: csrc/fa2_bindings.cpp.i
.PHONY : csrc/fa2_bindings.i

# target to preprocess a source file
csrc/fa2_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_fa2.dir/build.make CMakeFiles/flash_rt_fa2.dir/csrc/fa2_bindings.cpp.i
.PHONY : csrc/fa2_bindings.cpp.i

csrc/fa2_bindings.s: csrc/fa2_bindings.cpp.s
.PHONY : csrc/fa2_bindings.s

# target to generate assembly for a file
csrc/fa2_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_fa2.dir/build.make CMakeFiles/flash_rt_fa2.dir/csrc/fa2_bindings.cpp.s
.PHONY : csrc/fa2_bindings.cpp.s

csrc/gemm/cutlass_ada_fp8_gemm.o: csrc/gemm/cutlass_ada_fp8_gemm.cu.o
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.o

# target to build an object file
csrc/gemm/cutlass_ada_fp8_gemm.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm.cu.o
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.cu.o

csrc/gemm/cutlass_ada_fp8_gemm.i: csrc/gemm/cutlass_ada_fp8_gemm.cu.i
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.i

# target to preprocess a source file
csrc/gemm/cutlass_ada_fp8_gemm.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm.cu.i
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.cu.i

csrc/gemm/cutlass_ada_fp8_gemm.s: csrc/gemm/cutlass_ada_fp8_gemm.cu.s
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.s

# target to generate assembly for a file
csrc/gemm/cutlass_ada_fp8_gemm.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm.cu.s
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm.cu.s

csrc/gemm/cutlass_ada_fp8_gemm_simple.o: csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.o
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.o

# target to build an object file
csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_simple_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_simple_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.o
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.o

csrc/gemm/cutlass_ada_fp8_gemm_simple.i: csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.i
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.i

# target to preprocess a source file
csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_simple_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_simple_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.i
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.i

csrc/gemm/cutlass_ada_fp8_gemm_simple.s: csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.s
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.s

# target to generate assembly for a file
csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutlass_ada_fp8_simple_obj.dir/build.make CMakeFiles/cutlass_ada_fp8_simple_obj.dir/csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.s
.PHONY : csrc/gemm/cutlass_ada_fp8_gemm_simple.cu.s

csrc/gemm/gemm_runner.o: csrc/gemm/gemm_runner.cu.o
.PHONY : csrc/gemm/gemm_runner.o

# target to build an object file
csrc/gemm/gemm_runner.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/gemm/gemm_runner.cu.o
.PHONY : csrc/gemm/gemm_runner.cu.o

csrc/gemm/gemm_runner.i: csrc/gemm/gemm_runner.cu.i
.PHONY : csrc/gemm/gemm_runner.i

# target to preprocess a source file
csrc/gemm/gemm_runner.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/gemm/gemm_runner.cu.i
.PHONY : csrc/gemm/gemm_runner.cu.i

csrc/gemm/gemm_runner.s: csrc/gemm/gemm_runner.cu.s
.PHONY : csrc/gemm/gemm_runner.s

# target to generate assembly for a file
csrc/gemm/gemm_runner.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/gemm/gemm_runner.cu.s
.PHONY : csrc/gemm/gemm_runner.cu.s

csrc/kernels/activation.o: csrc/kernels/activation.cu.o
.PHONY : csrc/kernels/activation.o

# target to build an object file
csrc/kernels/activation.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/activation.cu.o
.PHONY : csrc/kernels/activation.cu.o

csrc/kernels/activation.i: csrc/kernels/activation.cu.i
.PHONY : csrc/kernels/activation.i

# target to preprocess a source file
csrc/kernels/activation.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/activation.cu.i
.PHONY : csrc/kernels/activation.cu.i

csrc/kernels/activation.s: csrc/kernels/activation.cu.s
.PHONY : csrc/kernels/activation.s

# target to generate assembly for a file
csrc/kernels/activation.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/activation.cu.s
.PHONY : csrc/kernels/activation.cu.s

csrc/kernels/attention_cublas.o: csrc/kernels/attention_cublas.cu.o
.PHONY : csrc/kernels/attention_cublas.o

# target to build an object file
csrc/kernels/attention_cublas.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_cublas.cu.o
.PHONY : csrc/kernels/attention_cublas.cu.o

csrc/kernels/attention_cublas.i: csrc/kernels/attention_cublas.cu.i
.PHONY : csrc/kernels/attention_cublas.i

# target to preprocess a source file
csrc/kernels/attention_cublas.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_cublas.cu.i
.PHONY : csrc/kernels/attention_cublas.cu.i

csrc/kernels/attention_cublas.s: csrc/kernels/attention_cublas.cu.s
.PHONY : csrc/kernels/attention_cublas.s

# target to generate assembly for a file
csrc/kernels/attention_cublas.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_cublas.cu.s
.PHONY : csrc/kernels/attention_cublas.cu.s

csrc/kernels/attention_dit_bf16.o: csrc/kernels/attention_dit_bf16.cu.o
.PHONY : csrc/kernels/attention_dit_bf16.o

# target to build an object file
csrc/kernels/attention_dit_bf16.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_dit_bf16.cu.o
.PHONY : csrc/kernels/attention_dit_bf16.cu.o

csrc/kernels/attention_dit_bf16.i: csrc/kernels/attention_dit_bf16.cu.i
.PHONY : csrc/kernels/attention_dit_bf16.i

# target to preprocess a source file
csrc/kernels/attention_dit_bf16.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_dit_bf16.cu.i
.PHONY : csrc/kernels/attention_dit_bf16.cu.i

csrc/kernels/attention_dit_bf16.s: csrc/kernels/attention_dit_bf16.cu.s
.PHONY : csrc/kernels/attention_dit_bf16.s

# target to generate assembly for a file
csrc/kernels/attention_dit_bf16.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_dit_bf16.cu.s
.PHONY : csrc/kernels/attention_dit_bf16.cu.s

csrc/kernels/attention_mha.o: csrc/kernels/attention_mha.cu.o
.PHONY : csrc/kernels/attention_mha.o

# target to build an object file
csrc/kernels/attention_mha.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha.cu.o
.PHONY : csrc/kernels/attention_mha.cu.o

csrc/kernels/attention_mha.i: csrc/kernels/attention_mha.cu.i
.PHONY : csrc/kernels/attention_mha.i

# target to preprocess a source file
csrc/kernels/attention_mha.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha.cu.i
.PHONY : csrc/kernels/attention_mha.cu.i

csrc/kernels/attention_mha.s: csrc/kernels/attention_mha.cu.s
.PHONY : csrc/kernels/attention_mha.s

# target to generate assembly for a file
csrc/kernels/attention_mha.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha.cu.s
.PHONY : csrc/kernels/attention_mha.cu.s

csrc/kernels/attention_mha_causal.o: csrc/kernels/attention_mha_causal.cu.o
.PHONY : csrc/kernels/attention_mha_causal.o

# target to build an object file
csrc/kernels/attention_mha_causal.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha_causal.cu.o
.PHONY : csrc/kernels/attention_mha_causal.cu.o

csrc/kernels/attention_mha_causal.i: csrc/kernels/attention_mha_causal.cu.i
.PHONY : csrc/kernels/attention_mha_causal.i

# target to preprocess a source file
csrc/kernels/attention_mha_causal.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha_causal.cu.i
.PHONY : csrc/kernels/attention_mha_causal.cu.i

csrc/kernels/attention_mha_causal.s: csrc/kernels/attention_mha_causal.cu.s
.PHONY : csrc/kernels/attention_mha_causal.s

# target to generate assembly for a file
csrc/kernels/attention_mha_causal.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/attention_mha_causal.cu.s
.PHONY : csrc/kernels/attention_mha_causal.cu.s

csrc/kernels/decoder_fused.o: csrc/kernels/decoder_fused.cu.o
.PHONY : csrc/kernels/decoder_fused.o

# target to build an object file
csrc/kernels/decoder_fused.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/decoder_fused.cu.o
.PHONY : csrc/kernels/decoder_fused.cu.o

csrc/kernels/decoder_fused.i: csrc/kernels/decoder_fused.cu.i
.PHONY : csrc/kernels/decoder_fused.i

# target to preprocess a source file
csrc/kernels/decoder_fused.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/decoder_fused.cu.i
.PHONY : csrc/kernels/decoder_fused.cu.i

csrc/kernels/decoder_fused.s: csrc/kernels/decoder_fused.cu.s
.PHONY : csrc/kernels/decoder_fused.s

# target to generate assembly for a file
csrc/kernels/decoder_fused.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/decoder_fused.cu.s
.PHONY : csrc/kernels/decoder_fused.cu.s

csrc/kernels/dit_bf16.o: csrc/kernels/dit_bf16.cu.o
.PHONY : csrc/kernels/dit_bf16.o

# target to build an object file
csrc/kernels/dit_bf16.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/dit_bf16.cu.o
.PHONY : csrc/kernels/dit_bf16.cu.o

csrc/kernels/dit_bf16.i: csrc/kernels/dit_bf16.cu.i
.PHONY : csrc/kernels/dit_bf16.i

# target to preprocess a source file
csrc/kernels/dit_bf16.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/dit_bf16.cu.i
.PHONY : csrc/kernels/dit_bf16.cu.i

csrc/kernels/dit_bf16.s: csrc/kernels/dit_bf16.cu.s
.PHONY : csrc/kernels/dit_bf16.s

# target to generate assembly for a file
csrc/kernels/dit_bf16.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/dit_bf16.cu.s
.PHONY : csrc/kernels/dit_bf16.cu.s

csrc/kernels/elementwise.o: csrc/kernels/elementwise.cu.o
.PHONY : csrc/kernels/elementwise.o

# target to build an object file
csrc/kernels/elementwise.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/elementwise.cu.o
.PHONY : csrc/kernels/elementwise.cu.o

csrc/kernels/elementwise.i: csrc/kernels/elementwise.cu.i
.PHONY : csrc/kernels/elementwise.i

# target to preprocess a source file
csrc/kernels/elementwise.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/elementwise.cu.i
.PHONY : csrc/kernels/elementwise.cu.i

csrc/kernels/elementwise.s: csrc/kernels/elementwise.cu.s
.PHONY : csrc/kernels/elementwise.s

# target to generate assembly for a file
csrc/kernels/elementwise.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/elementwise.cu.s
.PHONY : csrc/kernels/elementwise.cu.s

csrc/kernels/fusion.o: csrc/kernels/fusion.cu.o
.PHONY : csrc/kernels/fusion.o

# target to build an object file
csrc/kernels/fusion.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/fusion.cu.o
.PHONY : csrc/kernels/fusion.cu.o

csrc/kernels/fusion.i: csrc/kernels/fusion.cu.i
.PHONY : csrc/kernels/fusion.i

# target to preprocess a source file
csrc/kernels/fusion.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/fusion.cu.i
.PHONY : csrc/kernels/fusion.cu.i

csrc/kernels/fusion.s: csrc/kernels/fusion.cu.s
.PHONY : csrc/kernels/fusion.s

# target to generate assembly for a file
csrc/kernels/fusion.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/fusion.cu.s
.PHONY : csrc/kernels/fusion.cu.s

csrc/kernels/norm.o: csrc/kernels/norm.cu.o
.PHONY : csrc/kernels/norm.o

# target to build an object file
csrc/kernels/norm.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/norm.cu.o
.PHONY : csrc/kernels/norm.cu.o

csrc/kernels/norm.i: csrc/kernels/norm.cu.i
.PHONY : csrc/kernels/norm.i

# target to preprocess a source file
csrc/kernels/norm.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/norm.cu.i
.PHONY : csrc/kernels/norm.cu.i

csrc/kernels/norm.s: csrc/kernels/norm.cu.s
.PHONY : csrc/kernels/norm.s

# target to generate assembly for a file
csrc/kernels/norm.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/norm.cu.s
.PHONY : csrc/kernels/norm.cu.s

csrc/kernels/patch_embed.o: csrc/kernels/patch_embed.cu.o
.PHONY : csrc/kernels/patch_embed.o

# target to build an object file
csrc/kernels/patch_embed.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/patch_embed.cu.o
.PHONY : csrc/kernels/patch_embed.cu.o

csrc/kernels/patch_embed.i: csrc/kernels/patch_embed.cu.i
.PHONY : csrc/kernels/patch_embed.i

# target to preprocess a source file
csrc/kernels/patch_embed.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/patch_embed.cu.i
.PHONY : csrc/kernels/patch_embed.cu.i

csrc/kernels/patch_embed.s: csrc/kernels/patch_embed.cu.s
.PHONY : csrc/kernels/patch_embed.s

# target to generate assembly for a file
csrc/kernels/patch_embed.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/patch_embed.cu.s
.PHONY : csrc/kernels/patch_embed.cu.s

csrc/kernels/quantize.o: csrc/kernels/quantize.cu.o
.PHONY : csrc/kernels/quantize.o

# target to build an object file
csrc/kernels/quantize.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/quantize.cu.o
.PHONY : csrc/kernels/quantize.cu.o

csrc/kernels/quantize.i: csrc/kernels/quantize.cu.i
.PHONY : csrc/kernels/quantize.i

# target to preprocess a source file
csrc/kernels/quantize.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/quantize.cu.i
.PHONY : csrc/kernels/quantize.cu.i

csrc/kernels/quantize.s: csrc/kernels/quantize.cu.s
.PHONY : csrc/kernels/quantize.s

# target to generate assembly for a file
csrc/kernels/quantize.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/quantize.cu.s
.PHONY : csrc/kernels/quantize.cu.s

csrc/kernels/rope.o: csrc/kernels/rope.cu.o
.PHONY : csrc/kernels/rope.o

# target to build an object file
csrc/kernels/rope.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope.cu.o
.PHONY : csrc/kernels/rope.cu.o

csrc/kernels/rope.i: csrc/kernels/rope.cu.i
.PHONY : csrc/kernels/rope.i

# target to preprocess a source file
csrc/kernels/rope.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope.cu.i
.PHONY : csrc/kernels/rope.cu.i

csrc/kernels/rope.s: csrc/kernels/rope.cu.s
.PHONY : csrc/kernels/rope.s

# target to generate assembly for a file
csrc/kernels/rope.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope.cu.s
.PHONY : csrc/kernels/rope.cu.s

csrc/kernels/rope_qwen3.o: csrc/kernels/rope_qwen3.cu.o
.PHONY : csrc/kernels/rope_qwen3.o

# target to build an object file
csrc/kernels/rope_qwen3.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope_qwen3.cu.o
.PHONY : csrc/kernels/rope_qwen3.cu.o

csrc/kernels/rope_qwen3.i: csrc/kernels/rope_qwen3.cu.i
.PHONY : csrc/kernels/rope_qwen3.i

# target to preprocess a source file
csrc/kernels/rope_qwen3.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope_qwen3.cu.i
.PHONY : csrc/kernels/rope_qwen3.cu.i

csrc/kernels/rope_qwen3.s: csrc/kernels/rope_qwen3.cu.s
.PHONY : csrc/kernels/rope_qwen3.s

# target to generate assembly for a file
csrc/kernels/rope_qwen3.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/rope_qwen3.cu.s
.PHONY : csrc/kernels/rope_qwen3.cu.s

csrc/kernels/softmax.o: csrc/kernels/softmax.cu.o
.PHONY : csrc/kernels/softmax.o

# target to build an object file
csrc/kernels/softmax.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/softmax.cu.o
.PHONY : csrc/kernels/softmax.cu.o

csrc/kernels/softmax.i: csrc/kernels/softmax.cu.i
.PHONY : csrc/kernels/softmax.i

# target to preprocess a source file
csrc/kernels/softmax.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/softmax.cu.i
.PHONY : csrc/kernels/softmax.cu.i

csrc/kernels/softmax.s: csrc/kernels/softmax.cu.s
.PHONY : csrc/kernels/softmax.s

# target to generate assembly for a file
csrc/kernels/softmax.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash_rt_kernels.dir/build.make CMakeFiles/flash_rt_kernels.dir/csrc/kernels/softmax.cu.s
.PHONY : csrc/kernels/softmax.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cutlass_ada_fp8_obj"
	@echo "... cutlass_ada_fp8_simple_obj"
	@echo "... fa2_vendor_obj"
	@echo "... flash_rt_fa2"
	@echo "... flash_rt_kernels"
	@echo "... csrc/attention/fa2_wrapper.o"
	@echo "... csrc/attention/fa2_wrapper.i"
	@echo "... csrc/attention/fa2_wrapper.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim128_fp16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim256_fp16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_hdim96_fp16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim128_fp16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim256_fp16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_bf16_sm80.s"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.o"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.i"
	@echo "... csrc/attention/flash_attn_2_src/flash_attn/flash_fwd_split_hdim96_fp16_sm80.s"
	@echo "... csrc/attention/fmha_dispatch.o"
	@echo "... csrc/attention/fmha_dispatch.i"
	@echo "... csrc/attention/fmha_dispatch.s"
	@echo "... csrc/bindings.o"
	@echo "... csrc/bindings.i"
	@echo "... csrc/bindings.s"
	@echo "... csrc/fa2_bindings.o"
	@echo "... csrc/fa2_bindings.i"
	@echo "... csrc/fa2_bindings.s"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm.o"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm.i"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm.s"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm_simple.o"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm_simple.i"
	@echo "... csrc/gemm/cutlass_ada_fp8_gemm_simple.s"
	@echo "... csrc/gemm/gemm_runner.o"
	@echo "... csrc/gemm/gemm_runner.i"
	@echo "... csrc/gemm/gemm_runner.s"
	@echo "... csrc/kernels/activation.o"
	@echo "... csrc/kernels/activation.i"
	@echo "... csrc/kernels/activation.s"
	@echo "... csrc/kernels/attention_cublas.o"
	@echo "... csrc/kernels/attention_cublas.i"
	@echo "... csrc/kernels/attention_cublas.s"
	@echo "... csrc/kernels/attention_dit_bf16.o"
	@echo "... csrc/kernels/attention_dit_bf16.i"
	@echo "... csrc/kernels/attention_dit_bf16.s"
	@echo "... csrc/kernels/attention_mha.o"
	@echo "... csrc/kernels/attention_mha.i"
	@echo "... csrc/kernels/attention_mha.s"
	@echo "... csrc/kernels/attention_mha_causal.o"
	@echo "... csrc/kernels/attention_mha_causal.i"
	@echo "... csrc/kernels/attention_mha_causal.s"
	@echo "... csrc/kernels/decoder_fused.o"
	@echo "... csrc/kernels/decoder_fused.i"
	@echo "... csrc/kernels/decoder_fused.s"
	@echo "... csrc/kernels/dit_bf16.o"
	@echo "... csrc/kernels/dit_bf16.i"
	@echo "... csrc/kernels/dit_bf16.s"
	@echo "... csrc/kernels/elementwise.o"
	@echo "... csrc/kernels/elementwise.i"
	@echo "... csrc/kernels/elementwise.s"
	@echo "... csrc/kernels/fusion.o"
	@echo "... csrc/kernels/fusion.i"
	@echo "... csrc/kernels/fusion.s"
	@echo "... csrc/kernels/norm.o"
	@echo "... csrc/kernels/norm.i"
	@echo "... csrc/kernels/norm.s"
	@echo "... csrc/kernels/patch_embed.o"
	@echo "... csrc/kernels/patch_embed.i"
	@echo "... csrc/kernels/patch_embed.s"
	@echo "... csrc/kernels/quantize.o"
	@echo "... csrc/kernels/quantize.i"
	@echo "... csrc/kernels/quantize.s"
	@echo "... csrc/kernels/rope.o"
	@echo "... csrc/kernels/rope.i"
	@echo "... csrc/kernels/rope.s"
	@echo "... csrc/kernels/rope_qwen3.o"
	@echo "... csrc/kernels/rope_qwen3.i"
	@echo "... csrc/kernels/rope_qwen3.s"
	@echo "... csrc/kernels/softmax.o"
	@echo "... csrc/kernels/softmax.i"
	@echo "... csrc/kernels/softmax.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

