# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flashrt_pb2 as flashrt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flashrt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlashRTServiceStub(object):
    """FlashRT Inference Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/flashrt.FlashRTService/Health',
                request_serializer=flashrt__pb2.HealthRequest.SerializeToString,
                response_deserializer=flashrt__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/flashrt.FlashRTService/GetStats',
                request_serializer=flashrt__pb2.StatsRequest.SerializeToString,
                response_deserializer=flashrt__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/flashrt.FlashRTService/Infer',
                request_serializer=flashrt__pb2.InferRequest.SerializeToString,
                response_deserializer=flashrt__pb2.InferResponse.FromString,
                _registered_method=True)
        self.BatchInfer = channel.unary_unary(
                '/flashrt.FlashRTService/BatchInfer',
                request_serializer=flashrt__pb2.BatchInferRequest.SerializeToString,
                response_deserializer=flashrt__pb2.BatchInferResponse.FromString,
                _registered_method=True)
        self.SetPrompt = channel.unary_unary(
                '/flashrt.FlashRTService/SetPrompt',
                request_serializer=flashrt__pb2.PromptRequest.SerializeToString,
                response_deserializer=flashrt__pb2.PromptResponse.FromString,
                _registered_method=True)
        self.BuildPipeline = channel.unary_unary(
                '/flashrt.FlashRTService/BuildPipeline',
                request_serializer=flashrt__pb2.BuildRequest.SerializeToString,
                response_deserializer=flashrt__pb2.BuildResponse.FromString,
                _registered_method=True)


class FlashRTServiceServicer(object):
    """FlashRT Inference Service
    """

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Single inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInfer(self, request, context):
        """Batch inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPrompt(self, request, context):
        """Set prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildPipeline(self, request, context):
        """Build pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlashRTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=flashrt__pb2.HealthRequest.FromString,
                    response_serializer=flashrt__pb2.HealthResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=flashrt__pb2.StatsRequest.FromString,
                    response_serializer=flashrt__pb2.StatsResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=flashrt__pb2.InferRequest.FromString,
                    response_serializer=flashrt__pb2.InferResponse.SerializeToString,
            ),
            'BatchInfer': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInfer,
                    request_deserializer=flashrt__pb2.BatchInferRequest.FromString,
                    response_serializer=flashrt__pb2.BatchInferResponse.SerializeToString,
            ),
            'SetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPrompt,
                    request_deserializer=flashrt__pb2.PromptRequest.FromString,
                    response_serializer=flashrt__pb2.PromptResponse.SerializeToString,
            ),
            'BuildPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildPipeline,
                    request_deserializer=flashrt__pb2.BuildRequest.FromString,
                    response_serializer=flashrt__pb2.BuildResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flashrt.FlashRTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flashrt.FlashRTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlashRTService(object):
    """FlashRT Inference Service
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/Health',
            flashrt__pb2.HealthRequest.SerializeToString,
            flashrt__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/GetStats',
            flashrt__pb2.StatsRequest.SerializeToString,
            flashrt__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/Infer',
            flashrt__pb2.InferRequest.SerializeToString,
            flashrt__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/BatchInfer',
            flashrt__pb2.BatchInferRequest.SerializeToString,
            flashrt__pb2.BatchInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/SetPrompt',
            flashrt__pb2.PromptRequest.SerializeToString,
            flashrt__pb2.PromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashrt.FlashRTService/BuildPipeline',
            flashrt__pb2.BuildRequest.SerializeToString,
            flashrt__pb2.BuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
